* NumPy provides `array` type which is similar to Python's built-in `list` type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

In [1]:
# Versio check
import numpy as np
np.__version__

'1.15.1'

<h1> Understanding Data Types in Python </h1>

| Data type    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)|
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)|
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)|
| ``int8``      | Byte (-128 to 127)|
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)|
| ``uint8``     | Unsigned integer (0 to 255)|
| ``uint16``    | Unsigned integer (0 to 65535)|
| ``uint32``    | Unsigned integer (0 to 4294967295)|
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)|
| ``float_``    | Shorthand for ``float64``.|
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| ``complex_``  | Shorthand for ``complex128``.|
| ``complex64`` | Complex number, represented by two 32-bit floats|
| ``complex128``| Complex number, represented by two 64-bit floats|

* Python is dynamically-typed languages which it infer the type of variables without any specific declaration.
* In addition, Python variables cotain extra information about the tyope of the value
* Because standard Python implementation is written in C, every Python object is simlpy a cleverly-disguised C structure.

<h2> Python Integer Case </h2>

From Python 3.4 source code. `x=10000` is as follows:
```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

It divided into 4 parts:
* `ob_refcnt`, a reference count that helps Python sliently handle memory allocation and deallocation
* `PyTypeObject`, which encodes the type of the variable
* `ob_size`, which specifies the size of the following data members
* `ob_digit`, which contains the actual integer value that we expect the Python variable to represent

Notice the difference here: a C integer is essentially a label for a position in memory whose bytes encode an integer value. A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically. All this additional information in Python types comes at a cost, however, which becomes especially apparent in structures that combine many of these objects.

<h2> Python List Case </h2>

* The difference between a dynamic-type list and a fixed-type (NumPy-style) array : At the implementation level, the array essentially contains a single pointer to one contiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.

In [2]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Creating Arrays from Python Lists

In [3]:
np.array([1, 4, 2, 5, 3])
np.array([1, 2, 3, 4], dtype='float32')
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([1, 4, 2, 5, 3])

array([1., 2., 3., 4.], dtype=float32)

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Create Common Arrays

In [15]:
# Create wiht fixed value
np.zeros(10, dtype=int) # default : int64 as NumPy datatype
np.ones((3, 5), dtype=float) # default : float64 as NumPy datatype
np.zeros(10, dtype='int16')
np.full((3, 5), 3.14)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
# Create sequaltially
np.arange(0, 20, 2)
np.linspace(0, 1, 5)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Create randomly
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
np.random.randint(0, 10, (3, 3))
np.eye(3)

array([[0.86597514, 0.66661937, 0.08618114],
       [0.88209025, 0.10121624, 0.72826038],
       [0.49246475, 0.61297072, 0.44434698]])

array([[-1.2638839 ,  0.1037863 , -0.26233179],
       [ 0.89578522, -0.13911297,  0.86952407],
       [-0.94618655,  1.35526246, -0.0723526 ]])

array([[2, 8, 9],
       [3, 5, 4],
       [6, 5, 7]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])