# Aggregations: Min, Max and Everythig In Between

### Summing the Values in an array
* `np.sum` executes much faster than `sum` because it executes the operation in compiled code
* Also, `np.min, np.max` execute much faster than `min, max`

In [2]:
import numpy as np
L = np.random.rand(10000)
%timeit sum(L)
%timeit np.sum(L)

678 µs ± 7.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.55 µs ± 51.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%timeit min(L)
%timeit np.min(L)

539 µs ± 5.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.96 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Multi dimensional aggregates

One common type of aggregation operation is an aggregate along a row or column. Say you have some data stored in a two-dimensional array: The way the axis is specified here can be confusing to users coming from other languages. ***The axis keyword specifies the dimension of the array that will be collapsed***, rather than the dimension that will be returned. So specifying axis=0 means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

In [5]:
M = np.random.random((3, 4, 2))
M
M.shape

M.sum()

M.min(axis=0)
M.min(axis=0).shape

M.max(axis=-1)
M.max(axis=-1).shape

array([[[0.42547516, 0.88476917],
        [0.66955192, 0.41211739],
        [0.31417494, 0.30410938],
        [0.01431775, 0.37463418]],

       [[0.94202344, 0.99525784],
        [0.92918405, 0.522185  ],
        [0.08685937, 0.76713619],
        [0.69993992, 0.86048364]],

       [[0.06538234, 0.56991753],
        [0.75979693, 0.1020779 ],
        [0.26444424, 0.98794466],
        [0.55298688, 0.49792852]]])

(3, 4, 2)

13.002698352104819

array([[0.06538234, 0.56991753],
       [0.66955192, 0.1020779 ],
       [0.08685937, 0.30410938],
       [0.01431775, 0.37463418]])

(4, 2)

array([[0.88476917, 0.66955192, 0.31417494, 0.37463418],
       [0.99525784, 0.92918405, 0.76713619, 0.86048364],
       [0.56991753, 0.75979693, 0.98794466, 0.55298688]])

(3, 4)

### Other aggregations function

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute median of elements                    |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |